### ISSUE TITLE
Error occured when change backbone

### ISSUE THREAD

**Issue by shadyatscu** [TomHacker/ImageCluster#1]
Hi, thank you for the great work! when i changed the backbone such as 'resnet50' or 'dense net' the same error occured: 
Traceback (most recent call last):
  File "/home/peter/python_project/project_image_clustering/main.py", line 21, in <module>
    m.imagecluster()
  File "/home/peter/python_project/project_image_clustering/model.py", line 174, in imagecluster
    self.kmeans()
  File "/home/peter/python_project/project_image_clustering/model.py", line 136, in kmeans
    x.append([float(t) for t in i.strip('[').strip(']').split(' ')])
  File "/home/peter/python_project/project_image_clustering/model.py", line 136, in <listcomp>
    x.append([float(t) for t in i.strip('[').strip(']').split(' ')])
ValueError: could not convert string to float: '...'

how could i fix it, is the other backbone available? when  i use the vgg16 vgg19 the code works well

**Comment by shadyatscu** [comment]
bug has been fixed by changing x.append([float(t) for t in i.strip('[').strip(']').split(' ')])   to 
x.append([float(t) for t in i.strip('[').strip(']').split(' ')] if t) 
thanks a lot!

**Comment by lucky1177214** [comment]
@shadyatscu 
hi, the following problems occur  f.to_csv('output/base_model_{}_feature_maps.csv'.format(self.base_model_name)) 
no such file
I cloned it without this file
I ask for your help ,thanks
